log_level = "warn"
outputs = "All"
position = "Top"
app_launcher_cmd = "vicinae vicinae://toggle"

[modules]
left = [ [ "appLauncher", "Updates", "Workspaces" ] ]
center = [ "WindowTitle" ]
right = [ "SystemInfo", [  "Tray", "Clock", "Privacy", "KeyboardLayout", "Settings" ] ]

[updates]
check_cmd = "checkupdates; paru -Qua"
update_cmd = 'alacritty -e bash -c "paru; echo Done - Press enter to exit; read" &'

[workspaces]
visibility_mode = "MonitorSpecific"
enable_workspace_filling = false

[[CustomModule]]
name = "appLauncher"
icon = "ó±—¼"
command = "vicinae vicinae://toggle"

[services.brightness]
enabled = false

[window_title]
truncate_title_after_length = 100

[keyboard_layout.labels]
"English (Macintosh, ABC, ANSI)" = "ðŸ‡ºðŸ‡¸"
"Russian" = "ðŸ‡·ðŸ‡º"

[system_info]
indicators = [ "Cpu", "Memory", "Temperature", "DownloadSpeed", "UploadSpeed" ]

[system_info.cpu]
warn_threshold = 70
alert_threshold = 80

[system_info.memory]
warn_threshold = 70
alert_threshold = 85

[system_info.disk]
warn_threshold = 80
alert_threshold = 90

[system_info.temperature]
warn_threshold = 70
alert_threshold = 80
sensor = "k10temp-pci-00c3 Tctl"

[media_player]
max_title_length = 100

[settings]
lock_cmd = "playerctl --all-players pause; hyprlock &"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "nm-connection-editor"
vpn_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "blueman-manager"
remove_airplane_btn = true
remove_idle_btn = true
indicators = [
  "Audio",
  "PowerProfile",
  "Network",
  "Vpn",
  "Bluetooth",
]

[appearance]
scale_factor = 1.2
font_name = "JetBrains Mono"
success_color = "#a6e3a1"
text_color = "#cdd6f4"
opacity = 0.7

workspace_colors = [ "#fab387", "#b4befe", "#cba6f7" ]

[appearance.primary_color]
base = "#fab387"
text = "#1e1e2e"

[appearance.danger_color]
base = "#f38ba8"
weak = "#f9e2af"

[appearance.background_color]
base = "#1e1e2e"
weak = "#313244"
strong = "#45475a"

[appearance.secondary_color]
base = "#11111b"
strong = "#1b1b25"
